name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Compile Java code
      run: |
        mkdir -p classes
        javac -d classes $(find src -name "*.java")
        
    - name: Build Docker image
      run: docker build -t ticket-queue-api .
      
    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 --name ticket-queue-container ticket-queue-api
        # Wait for the server to start
        sleep 200
        
    - name: Run tests
      run: |
        chmod +x test.sh
        ./test.sh
        
    - name: Stop Docker container
      run: docker stop ticket-queue-container